/** Rebuild with: node --import tsx apps/web/scripts/gen-harbor.tsx */
import React from 'react';
import { createHash } from 'node:crypto';
import { renderToStaticMarkup } from 'react-dom/server';
import { writeFileSync, mkdirSync } from 'node:fs';
import { Resvg } from '@resvg/resvg-js';
import { House, Tree, Barrel, Lamp, Table, Boat, Pot, P } from '../components/world/harbor-art';
import { HarborProp, HarborTower } from '../components/world/harbor-props';
const assets:Record<string,{src:string;w:number;x:number;y:number;width:number;height:number}>={};
const directory=new URL('../public/harbor/',import.meta.url);mkdirSync(directory,{recursive:true});
function add(name:string,node:React.ReactNode,w:number,anchor:[number,number],scale=1){
 const svg=renderToStaticMarkup(<svg xmlns="http://www.w3.org/2000/svg"><g transform={`scale(${scale}) translate(${-anchor[0]} ${-anchor[1]})`}>{node}</g></svg>)
 .replace(/<text\b[^>]*>[\s\S]*?<\/text>/g,'').replace(/\sfilter="[^"]*"/g,'').replace(/<polygon\b[^>]*fill="url\([^>]*\/>/g,'');
 const source=svg.replace('<svg ', '<svg width="1000" height="1000" viewBox="-500 -500 1000 1000" ');
 const bounds=new Resvg(source).getBBox();if(!bounds)throw new Error(`Empty artwork: ${name}`);
 const x=Math.floor(bounds.x)-2,y=Math.floor(bounds.y)-2,width=Math.ceil(bounds.width)+4,height=Math.ceil(bounds.height)+4;
 const cropped=source.replace('viewBox="-500 -500 1000 1000"',`viewBox="${x} ${y} ${width} ${height}"`).replace('width="1000" height="1000"',`width="${width}" height="${height}"`);
 const png=new Resvg(cropped,{fitTo:{mode:'zoom',value:3}}).render().asPng();
 writeFileSync(new URL(name+'.png',directory),png);
 const version=createHash('sha256').update(png).digest('hex').slice(0,10);
 assets[name]={src:'/harbor/'+name+'.png?v='+version,w:w*scale,x,y,width,height};
}
for(const [name,w,d,h,cafe,color,side] of [
 ['house',130,95,142,false,'#ece3cc','#c4c5ac'],['cottage',110,85,106,false,'#ddd5b8','#b8bca2'],
 ['shop',145,100,130,true,'#e4c4a0','#bbb59a'],['inn',160,110,192,false,'#ece3cc','#c4c5ac'],
 ['tavern',149,105,133,true,'#e4c4a0','#bbb59a'],['bakery',140,95,142,true,'#ead9b9','#c4bea2'],
 ['chandlery',100,80,158,false,'#d9d8be','#b4bca4'],['harbor-office',110,85,130,false,'#ddd5b8','#b8bca2'],
 ['smithy',132,100,102,true,'#d7ccb4','#afa991'],['fishhouse',125,85,90,true,'#d9d8be','#b4bca4'],
 ['boatshed',145,100,88,true,'#ddd5b8','#b8bca2'],['council',175,115,177,false,'#ece3cc','#c4c5ac'],
 ] as const) { add(name,<House u={0} v={0} w={w} d={d} h={h} name="" cafe={cafe} color={color} side={side}/>,(w+d)*.95,P(w,d),.72);
add(name+'-lit',<House u={0} v={0} w={w} d={d} h={h} name="" cafe={cafe} color={color} side={side} lit/>,(w+d)*.95,P(w,d),.72);
// A few colour-and-roof variants of the common houses, so a row of them never reads as clones. Base names are unchanged.
(({house:[['#e6d3b0','#c9c0a0',2],['#dbe0d2','#b6bfa8',4]],cottage:[['#e7d0ba','#c6bda0',3],['#d3dccd','#b2bca6',1]],shop:[['#e0d6c0','#bcb69a',5],['#e8cbb0','#c4b79a',2]]} as Record<string,[string,string,number][]>)[name]??[]).forEach(([vc,vs,vr],vi)=>{const vn=name+(vi+2);
add(vn,<House u={0} v={0} w={w} d={d} h={h} name="" cafe={cafe} color={vc} side={vs} roof={vr}/>,(w+d)*.95,P(w,d),.72);
add(vn+'-lit',<House u={0} v={0} w={w} d={d} h={h} name="" cafe={cafe} color={vc} side={vs} roof={vr} lit/>,(w+d)*.95,P(w,d),.72);}); }
add('tree-large',<Tree u={0} v={0}/>,110,P(0,0),1.3);
add('tree-small',<Tree u={0} v={0}/>,110,P(0,0),.8);
add('olive',<Tree u={0} v={0}/>,110,P(0,0),.85);
add('barrel',<Barrel u={0} v={0}/>,26,P(0,0),1);
add('lamp',<Lamp u={0} v={0} lit={false}/>,36,P(0,0),.72);
add('terrace',<Table u={0} v={0}/>,84,P(0,0),.85);
add('parasol',<Table u={0} v={0} parasol/>,110,P(0,0),.85);
add('rowboat',<Boat u={0} v={0}/>,120,P(0,0),.75);
add('planter',<Pot u={0} v={0} flowers/>,30,P(0,0),1.2);
for(const [kind,w] of [['boat',180],['net',100],['washing',140],['cloth',140],['bench',74],['wall',130],['crates',60],['fence',140],['pier',280],['rock',48],['searocks',90],['cypress',36],['bush',55],['stall',150],['sawpit',150],['well',65],['field',180],['orchard',180],['quarry',190]] as const)add(kind,<HarborProp kind={kind}/>,w,[0,0]);
for(const kind of ['mill','chapel','lighthouse'] as const)add(kind,<HarborTower kind={kind}/>,90,[0,0]);
writeFileSync(new URL('../components/world/harbor-atlas.ts',import.meta.url),'// Generated by scripts/gen-harbor.tsx from harbor-art.tsx. Do not edit by hand.\nexport const HARBOR_ATLAS = '+JSON.stringify(assets)+' as const;\n');
console.log(`Generated ${Object.keys(assets).length} Harbor Street drawings.`);
