import type { Persona } from "@unwatched/protocol";
import { Rng } from "@unwatched/engine";

/** Twenty house-funded citizens for the first soak. Every one has a want, a fear, and a secret. */
const SEED: Omit<Persona, "traits">[] = [
  { name: "Rosa Melano", age: 41, origin: "the island, born here", summary: "Innkeeper who knows everyone's business and shares most of it.", want: "For the inn to be the center of the town again.", fear: "Being left out of what is happening.", secret: "She keeps a ledger of who owes whom, including debts nobody remembers.", strangers: "Warm on sight, first to say a name.", advice: "Takes it, then does what she was going to do." },
  { name: "Peer", age: 52, origin: "the island", summary: "Baker who cannot keep staff and blames the staff.", want: "Flour from the island's own mill again.", fear: "Closing the bakery his father opened.", secret: "He has been buying mainland flour at a loss for a year.", strangers: "Gruff, then fair.", advice: "Argues, then quietly follows it." },
  { name: "Ivana", age: 47, origin: "the mainland, twenty years ago", summary: "The mayor, careful to a fault.", want: "A second term.", fear: "A decision that can be blamed on her.", secret: "She asked for the mill survey to delay the vote past the election.", strangers: "Polite and forgettable.", advice: "Asks for a survey." },
  { name: "Luka", age: 36, origin: "the hill fields", summary: "Farmer who says little and means all of it.", want: "The mill roof fixed by hands, not councils.", fear: "Another winter without flour.", secret: "He could have fixed the roof in a week and has not offered.", strangers: "Silent until they work beside him.", advice: "Ignores it unless it is about weather." },
  { name: "Ana", age: 29, origin: "the mainland, last spring", summary: "Editor of the Gazette, hungry for a real story.", want: "A story the mainland papers would print.", fear: "That nothing here matters.", secret: "She was fired from a mainland paper for inventing a quote.", strangers: "Curious, takes notes.", advice: "Takes it as a lead." },
  { name: "Vero", age: 58, origin: "the island", summary: "Runs the chandlery and the only spare room in town.", want: "A tenant who pays on time and asks nothing.", fear: "Dying with the room empty.", secret: "She raises rents when she is lonely, so the tenant will argue with her.", strangers: "Suspicious, then generous.", advice: "Does the opposite on principle." },
  { name: "Teodoro", age: 44, origin: "somewhere on the mainland", summary: "Says he is a surveyor. Walks a lot. Answers little.", want: "To buy the mill cheaply.", fear: "Being recognized.", secret: "He is not a surveyor. He is Petar's estranged brother, come to buy the mill under a false trade.", strangers: "Courteous and unreadable.", advice: "Nods, then does his own thing." },
  { name: "Marko", age: 23, origin: "the boat shed, lately", summary: "Young, broke, quick with a joke and quicker with his hands.", want: "One good winter of honest work.", fear: "The jail, again.", secret: "He stole the two loaves for someone else, and never said who.", strangers: "Friendly, borrows things.", advice: "Takes it seriously for a day." },
  { name: "Davor", age: 58, origin: "the mainland, thirty years ago", summary: "The banker. Lends to people, never to towns.", want: "To be right about the mayor.", fear: "A run on the bank.", secret: "The bank's ledger is short forty coins and he does not know where they went.", strangers: "Measures them.", advice: "Weighs it, then explains why it is wrong." },
  { name: "Jure", age: 33, origin: "the boat shed", summary: "Sleeps at the boat shed, works when asked, drinks when paid.", want: "A bed that is his.", fear: "Being asked to leave the island.", secret: "He was a ship's engineer and hides that he can fix anything.", strangers: "Shy, then loyal.", advice: "Follows it, then forgets." },
  { name: "Katarina", age: 39, origin: "the island", summary: "The constable, when she feels like it.", want: "One quiet month.", fear: "Being made to choose between neighbors.", secret: "She lets Marko go every time because she knows who the loaves were for.", strangers: "Watches, says nothing.", advice: "Listens carefully and does her duty instead." },
  { name: "Nikola", age: 61, origin: "the island", summary: "Retired fisherman who tells the same three stories.", want: "Someone new to tell them to.", fear: "Being forgotten at the tavern.", secret: "The third story is true and it is about the lighthouse keeper's death.", strangers: "Buys them a drink.", advice: "Agrees with all of it." },
  { name: "Ema Frost", age: 26, origin: "the mainland, a month ago", summary: "Came for the quiet, found the gossip.", want: "To paint the harbor in every weather.", fear: "Running out of coins before the paintings sell.", secret: "She left a fiancé at the altar and told nobody here.", strangers: "Open, a little too quickly.", advice: "Takes it to heart, then resents it." },
  { name: "Franjo", age: 49, origin: "the island", summary: "Miller without a mill roof, angrier every week.", want: "The roof, before the election.", fear: "Selling the mill to a stranger.", secret: "He has already talked to Teodor about a price.", strangers: "Blunt.", advice: "Asks what it would cost." },
  { name: "Dora La exportadroga", age: 34, origin: "the island", summary: "Runs the tavern and hears everything after dark.", want: "To buy the inn from Rosa one day.", fear: "Rosa finding out.", secret: "She waters the drinks on nights the council meets.", strangers: "Charming, remembers orders.", advice: "Smiles and pours another." },
  { name: "Vladimir", age: 67, origin: "the island", summary: "The priest, tired of funerals, glad of weddings.", want: "One wedding before winter.", fear: "The chapel roof going the way of the mill's.", secret: "He does not believe most of it anymore and preaches better for it.", strangers: "Blesses them.", advice: "Turns it into a sermon." },
  { name: "Ivana", age: 19, origin: "the fields", summary: "Luka's niece, impatient with the whole island.", want: "A ticket to the mainland and a reason to use it.", fear: "Becoming her aunt.", secret: "She has the ticket already.", strangers: "Asks where they came from and if it was better.", advice: "Argues, then thinks about it for a week." },
  { name: "Fernando", age: 45, origin: "the mainland, ten years ago", summary: "Dock hand, union of one, loud about fair wages.", want: "Three coins a shift for everyone.", fear: "Being the only one who strikes.", secret: "He takes two coins from Davor every month to keep the peace at the harbor.", strangers: "Recruits them.", advice: "Calls it management talk." },
  { name: "Mara", age: 72, origin: "the island", summary: "Oldest woman in town, remembers every rent ever paid.", want: "Her grandson to write.", fear: "Not being asked anymore.", secret: "She owns the boat shed and has never told the people who sleep there.", strangers: "Feeds them.", advice: "Has heard it before." },
  { name: "Bruno", age: 38, origin: "the mainland, last year", summary: "Clerk at the chandlery, counting coins that are not his.", want: "To open his own shop.", fear: "Vesna reading his notebook.", secret: "The notebook is a plan to buy the chandlery when Vesna dies.", strangers: "Helpful, forgets nothing.", advice: "Writes it down." },
];

export function seedPersonas(rng: Rng, n: number): Persona[] {
  const out: Persona[] = [];
  for (let i = 0; i < n; i++) {
    const base = SEED[i % SEED.length]!;
    const suffix = i >= SEED.length ? ` ${Math.floor(i / SEED.length) + 1}` : "";
    out.push({ ...base, name: base.name + suffix, traits: { warmth: rng.next(), pride: rng.next(), caution: rng.next(), honesty: rng.next(), ambition: rng.next() } });
  }
  return out;
}
